### ISSUE TITLE
Implement hover state for mission and vision

### ISSUE THREAD

**Issue by poly4concept** [zurichat/zc_plugin_company_goals#148]
Company's mission and vision should have a hover state when a user hovers on them

**Comment by Asylcreek** [comment]
Would the texts not be too much for a hover? Would it not be better for the mission & vision to be on a separate route?

**Comment by poly4concept** [comment]
Yeah, it's not the whole mission and vision
like some sidebar navigation for the vision  and mission will be hoverable
but we are not using this one again sha, they will be closing them soon
Those latest issues in CAPS are the one they are using
