### ISSUE TITLE
CREATE A FORM COMPONENT FOR SETTING NEW GOALS

### ISSUE THREAD

**Issue by tundealabi** [zurichat/zc_plugin_company_goals#154]
- [ ] the form should show several fields required for creating a new goal
- [ ] the form should show a submit button
- [ ] the form should have a close button if the user wishes to opt-out

**Comment by masterd2020** [comment]
Cool, you description is top notch 😘

**Comment by abiona01** [comment]
Testing link: 
https://goals.zuri.chat/

Note: Click on the open modal button to view the create form modal. (The 'new goal' button is in a component that's not ready)
![screencapture-localhost-3000-2021-09-02-23_03_44](https://user-images.githubusercontent.com/70848491/131922340-bae7a0a8-88c6-4e0e-8217-247a85279af5.png)

**Comment by markessien** [comment]
Nice work :+1:
