### ISSUE TITLE
EDIT COMPANY VISION STATEMENT

### ISSUE THREAD

**Issue by Kezykeen** [zurichat/zc_plugin_company_goals#320]
- [ ] Create a button that allows the user edit statement
- [ ] Create an edit statement view

**Comment by Ibrahim-Isah** [comment]
Pull request #369 

goals.zuri.chat

![Screenshot_20210902-223744_1](https://user-images.githubusercontent.com/38298865/131935326-0e969b0b-1222-44dd-b4ec-494e5e24babb.png)

**Comment by markessien** [comment]
Nice work :+1:
